name: "MuscleBook"
description: "MuscleBook"
version: "0.0.1"
slug: "MuscleBook"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
uart: true
options:
  loglevel: "Information"
  serialport: "/dev/ttyUSB0"
  easywaveactiontimeout: 500
  easywaverepeattimeout: 80
  mqttserver: 192.168.0.12
  mqttport: 1883
  mqttuser: "mqtt"
  mqttpassword: "mqtt"
schema:
  loglevel: list(Verbose|Debug|Information|Warning|Error|Fatal)
  serialport: device(subsystem=tty)
  easywaveactiontimeout: int
  easywaverepeattimeout: int
  mqttserver: str
  mqttport: port
  mqttuser: str
  mqttpassword: password